### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by chuwy** [migtavares/owmClient#5]
I couldn't find any Install instructions or any other clues how I can start to use owmClient in my library beside of put compiled jar into `lib`.
It could be very useful to add Getting started note.

**Comment by migtavares** [comment]
True... that is something that I have to look into.

**Comment by migtavares** [comment]
Hello, 

I finally found the time to do some research on how to publish artefacts. Also updated the Readme on how to use the library.

I'm using the OSSRH repository. Let me know if it does work as expected.
